name: workflow1
on: 
   push:
        branches:
        - main

job:
    job1:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v2
        - name: print message
          run: echo 'welcome to github action'




